/**
 *
 * 389. Find the Difference
 * Given two strings s and t which consist of only lowercase letters. String t is 
 * generated by random shuffling string s and then add one more letter at a random 
 * position.* Find the letter that was added in t.
 * Example:
 *     Input:
 *         s = "abcd"
 *         t = "abcde"
 *     Output:
 *         'e'
 *     Explanation:
 *         'e' is the letter that was added.
 *
 */
import java.util.*;

public class Solution {
	public char findTheDifference(String s, String t) {
		HashMap<Character, Integer> map = new HashMap<Character, Integer>();
		for (char c: s.toCharArray()) {
			int count = map.getOrDefault(c, 0) + 1;
			map.put(c, count);
		}
		
		for (char c: t.toCharArray()) {
			int count = map.getOrDefault(c, 0);
			if (count == 0) {
				return c;
			}
			map.put(c, count - 1);
		}
		return ' ';
	}
}